baseURL = "https://www.leanai.org"
languageCode = "en-us"
title = "Lean AI"
publishDir = "docs"
theme = "whisper"

pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
pygmentsUseClasses = true

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

[[menu.main]]
    #name = "Docs"
    #url = "/docs/"
    #weight = 2

[params]
  google_analytics_id=""
  #homepage_button_link = '/docs'
  #homepage_button_text = 'Read The Docs'
  homepage_intro = 'Lean AI is a non profit organization that governs sustainable development of Artificial Intelligence in organizations.'
  #homepage_image = '/images/terminal.gif'

  [params.homepage_meta_tags]
    meta_description = "Lean AI Stack for open source cloud agnostic end to end machine learning."
    meta_og_title = "Lean AI.org"
    meta_og_type = "website"
    meta_og_url = "https://leanai.org"
    meta_og_image = "https://leanai.org/images/leanai-logo.png"
    meta_og_description = "Lean AI Stack for open source cloud agnostic end to end machine learning."
    meta_twitter_card = "summary"
    meta_twitter_site = "@leanaiorg"
    meta_twitter_creator = "@leanaiorg"

  [params.logo]
      mobile = "/images/leanai-logo.png"
      standard  = "/images/leanai-logo.png"
